version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile-express
    ports:
      - "4000:4000"
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
