global: 
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs: 
  - job_name: "prometheus"
    static_configs: 
      - targets: ["host.docker.internal:9090"]
  
  - job_name: "grafana"
    static_configs: 
      - targets: ["host.docker.internal:3000"]
  
  - job_name: "games_api"
    metrics_path: /metrics-text
    static_configs: 
      - targets: ["host.docker.internal:4000"]